; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; AUTOMATICALLY GENERATED CODE, DO NOT MODIFY
; UNLESS YOU REALLY, REALLY, REALLY MEAN IT !!
; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; Code generated by : Dev-Object - V2.2.5
; Project name : Dev-Board
; File name : DevBoard - DevBoard.pbi
; File Version : 1.0.0
; Programmation : In progress
; Programmed by : Guillaume Saumure
; AKA : StarBootics
; E-mail : gsaumure@cgocable.ca
; Creation Date : June 17th, 2024
; Last update : June 22nd, 2024
; Coded for PureBasic : V6.11 LTS
; Platform : Windows, Linux, MacOS X
; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; This is free and unencumbered software released into the public domain.
; 
; Anyone is free to copy, modify, publish, use, compile, sell, or
; distribute this software, either in source code form or as a compiled
; binary, for any purpose, commercial or non-commercial, and by any
; means.
; 
; In jurisdictions that recognize copyright laws, the author or authors
; of this software dedicate any and all copyright interest in the
; software to the public domain. We make this dedication for the benefit
; of the public at large and to the detriment of our heirs and
; successors. We intend this dedication to be an overt act of
; relinquishment in perpetuity of all present and future rights to this
; software under copyright law.
; 
; THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
; EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
; MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
; IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
; OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
; ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
; OTHER DEALINGS IN THE SOFTWARE.
; 
; For more information, please refer to <http://unlicense.org/>
; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

DeclareModule DevBoard
  
  Interface DevBoard
    
    CreateWindow()
    EventManager()
    Shutdown()
    Free()
    
  EndInterface
  
  Declare.i New()
  
EndDeclareModule

Module DevBoard
  
  ;DisableDebugger
  
  ; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  ; <<<<< Constants Enumaration <<<<<
  
  Enumeration
    
    #MainWindow
    #NewProjectWindow
    #AddCardWindow
    #EditCardWindow
    #OptionsSettingsWindow
    #MoveCardWindow
    #ArchiveWindow
    #TrashWindow
    
    #ScrollAreaBoard
    #CanvasBoard
    
    #ButtonNew
    #ButtonOpen
    #ButtonSave
    #ButtonOptions
    #ButtonAddCard
    #ButtonEditCard
    #ButtonRemoveCard
    #ButtonMoveCard
    #ButtonArchive
    #ButtonTrash
    
    #TextNewNewProjectName
    #StringNewNewProjectName
    #ButtonNewProjectCreate
    #ButtonNewProjectCancel
    
    #TextAddCardCardTitle
    #StringAddCardCardTitle
    
    #TextAddCardCardDescription
    #EditorAddCardCardDescription
    
    #OptionAddCardToIdeas
    #OptionAddCardToInProgress
    #OptionAddCardToCompleted
    #OptionAddCardToAbandoned
    
    #ButtonAddCardCreate
    #ButtonAddCardCancel
    
    
    
    #TextEditCardCardTitle
    #StringEditCardCardTitle
    
    #TextEditCardCardDescription
    #EditorEditCardCardDescription
    
    #ButtonEditCardOK
    #ButtonEditCardCancel
    
    #OptionMoveCardDestinationA
    #OptionMoveCardDestinationB
    #OptionMoveCardDestinationC
    
    #ButtonMoveCardOK
    #ButtonMoveCardCancel
    
    #FrameChooseLanguage
    #ListViewChooseLanguage
    
    #FrameFontColor
    #TextFontName
    #StringFontName
    #ButtonChooseFont
    #TextFontSize
    #StringFontSize
    
    #TextBorderColor
    #TextListBackColor
    #TextCardBackColor
    #TextTextColor
    #TextSelectedBorderColor
    #TextFlyOverBorderColor
    
    #ColorPreviewBorderColor
    #ColorPreviewListBackColor
    #ColorPreviewCardBackColor
    #ColorPreviewTextColor
    #ColorPreviewSelectedBorderColor
    #ColorPreviewFlyOverBorderColor
    
    #FrameMoveCard
    #OptionMoveIn30Days
    #OptionMoveIn60Days
    #OptionMoveIn90Days
    
    #ButtonOptionsSettingsOK
    #ButtonOptionsSettingsCancel
    
    #ScrollAreaArchiveBoard
    #CanvasArchiveBoard
    
    #ButtonEmptyArchive
    #ButtonDeleteCardFromArchive
    #ButtonRestoreCardFromArchive
    
    #ButtonCloseArchiveManager
    
    #ScrollAreaTrashBoard
    #CanvasTrashBoard
    
    #ButtonEmptyTrash
    #ButtonDeleteCardFromTrash
    #ButtonRestoreCardFromTrash
    
    #ButtonCloseTrashManager
    

    
  EndEnumeration
  
  ; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  ; <<<<< Structure declaration <<<<<
  
  Structure Private_Members
    
    VirtualTable.i
    InstallPath.s
    UserPath.s
    PrefsFileName.s
    MainWindowSettings.WindowSettings::WindowSettings
    GeneralSettings.Setting::Setting
    MainBoard.BoardDrawingSystem::BoardDrawingSystem
    ArchiveBoard.BoardDrawingSystem::BoardDrawingSystem
    TrashBoard.BoardDrawingSystem::BoardDrawingSystem
    ArchiveButtonCtrl.TwinState::TwinState
    TrashButtonCtrl.TwinState::TwinState
    Project.Project::Project
    Language.Language::Language
    
  EndStructure
  
  ; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  ; <<<<< Create preferences file <<<<<
  
  Procedure CreatePrefs(*This.Private_Members)
    
    If CreatePreferences(*This\PrefsFileName)
      
      *This\MainWindowSettings\WritePrefs("MainWindowSettings")
      *This\GeneralSettings\WritePrefs("GeneralSettings")
      *This\Language\WritePrefs("Language")
      
      ClosePreferences()
      
    EndIf
    
  EndProcedure
  
  ; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  ; <<<<< Open preferences file <<<<<
  
  Procedure OpenPrefs(*This.Private_Members)
    
    If OpenPreferences(*This\PrefsFileName)
      
      *This\MainWindowSettings\ReadPrefs("MainWindowSettings")
      *This\GeneralSettings\ReadPrefs("GeneralSettings")
      *This\Language\ReadPrefs("Language")
      
      ClosePreferences()
      
    EndIf
    
  EndProcedure
  
  Procedure ButtonImageGroup(FirstGadgetID, LastGadgetID, X, Y, Width, Height, Gap = 5)
    
    For Gadget = FirstGadgetID To LastGadgetID 
      
      If IsImage(Gadget)
        ImageID = ImageID(Gadget)
      Else
        ImageID = 0
      EndIf
      
      ButtonImageGadget(Gadget, X, Y, Width, Height, ImageID)
      Y + Height + Gap 
      
    Next
    
  EndProcedure
  
  Procedure MoveButtonImageGroup(FirstGadgetID, LastGadgetID, X, Y, Gap = 5)
    
    For Gadget = FirstGadgetID To LastGadgetID 
      ResizeGadget(Gadget, X, Y, #PB_Ignore, #PB_Ignore)
      Y + GadgetHeight(Gadget) + Gap
    Next
    
  EndProcedure
  
  Procedure.s GenerateUUID()
    
    Protected UUID_String.s
    
    For Index = 0 To 15
      
      If Index = 7
        Value.a = 64 + Random(15)
      ElseIf Index = 9
        Value = 128 + Random(63)
      Else
        Value = Random(255)
      EndIf
      
      If Index = 3 Or Index = 5 Or Index = 7
        UUID_String + "-"
      EndIf
      
      UUID_String + RSet(Hex(Value), 2, "0")
      
    Next
    
    ProcedureReturn "{" + UUID_String + "}"
  EndProcedure
  
  Procedure Language_To_GUI(*This.Private_Members)
    
    If *This\Project\GetName() <> ""
      SetWindowTitle(#MainWindow, *This\Language\Message(Language::#PROGRAM_NAME) + " - " + *This\Project\GetName())
    Else
      SetWindowTitle(#MainWindow, *This\Language\Message(Language::#PROGRAM_NAME))
    EndIf
    
    *This\MainBoard\SetBoardDisplayName("Ideas", *This\Language\Message(Language::#BOARD_IDEAS_TODO))
    *This\MainBoard\SetBoardDisplayName("InProgress", *This\Language\Message(Language::#BOARD_IN_PROGRESS))
    *This\MainBoard\SetBoardDisplayName("Completed", *This\Language\Message(Language::#BOARD_COMPLETED))
    *This\MainBoard\SetBoardDisplayName("Abandoned", *This\Language\Message(Language::#BOARD_ABANDONED))
    
    GadgetToolTip(#ButtonNew, *This\Language\Message(Language::#TOOLTIP_NEW_PROJECT))
    GadgetToolTip(#ButtonOpen, *This\Language\Message(Language::#TOOLTIP_OPEN_PROJECT))
    GadgetToolTip(#ButtonSave, *This\Language\Message(Language::#TOOLTIP_SAVE_PROJECT))
    GadgetToolTip(#ButtonOptions, *This\Language\Message(Language::#TOOLTIP_OPTIONS))
    GadgetToolTip(#ButtonAddCard, *This\Language\Message(Language::#TOOLTIP_ADD_CARD))
    GadgetToolTip(#ButtonEditCard, *This\Language\Message(Language::#TOOLTIP_EDIT_CARD))
    GadgetToolTip(#ButtonRemoveCard, *This\Language\Message(Language::#TOOLTIP_REMOVE_CARD))
    GadgetToolTip(#ButtonMoveCard, *This\Language\Message(Language::#TOOLTIP_MOVE_CARD))
    GadgetToolTip(#ButtonArchive, *This\Language\Message(Language::#TOOLTIP_ARCHIVE))
    GadgetToolTip(#ButtonTrash, *This\Language\Message(Language::#TOOLTIP_TRASH))
    
  EndProcedure
  
  Procedure Project_To_GUI(*This.Private_Members)
    
    If *This\Project\GetName() <> ""
      SetWindowTitle(#MainWindow, *This\Language\Message(Language::#PROGRAM_NAME) + " - " + *This\Project\GetName())
    Else
      SetWindowTitle(#MainWindow, *This\Language\Message(Language::#PROGRAM_NAME))
    EndIf
    
    *This\Project\ResetListOfCardsList()
    
    While *This\Project\NextListOfCardsList()
      
      *ListOfCardsList.CardsList::CardsList = *This\Project\GetListOfCardsList()
      
      Select *ListOfCardsList\GetName() 
          
        Case "Ideas"
          *ListOfCardsList\ResetCards()
          
          While *ListOfCardsList\NextCards()
            *Card.Card::Card = *ListOfCardsList\GetCards()
            *This\MainBoard\AddBoardCard("Ideas", *Card\GetTitle(), *Card\GetDescription(), *Card\GetUUID())
          Wend
          
        Case "InProgress"
          
          *ListOfCardsList\ResetCards()
          
          While *ListOfCardsList\NextCards()
            *Card.Card::Card = *ListOfCardsList\GetCards()
            *This\MainBoard\AddBoardCard("InProgress", *Card\GetTitle(), *Card\GetDescription(), *Card\GetUUID())
          Wend
          
        Case "Completed"
          *ListOfCardsList\ResetCards()
          
          While *ListOfCardsList\NextCards()
            *Card.Card::Card = *ListOfCardsList\GetCards()
            *This\MainBoard\AddBoardCard("Completed", *Card\GetTitle(), *Card\GetDescription(), *Card\GetUUID())
          Wend
          
        Case "Abandoned"
          *ListOfCardsList\ResetCards()
          
          While *ListOfCardsList\NextCards()
            *Card.Card::Card = *ListOfCardsList\GetCards()
            *This\MainBoard\AddBoardCard("Abandoned", *Card\GetTitle(), *Card\GetDescription(), *Card\GetUUID())
          Wend
          
        Case "Archive"
          If *ListOfCardsList\CardsSize() >= 1
            *This\ArchiveButtonCtrl\SetStatus(1)
          Else
            *This\ArchiveButtonCtrl\SetStatus(0)
          EndIf
          
        Case "Trash"
          If *ListOfCardsList\CardsSize() >= 1
            *This\TrashButtonCtrl\SetStatus(1)
          Else
            *This\TrashButtonCtrl\SetStatus(0)
          EndIf
          
      EndSelect
      
    Wend
    
  EndProcedure
  
  Procedure MoveCardBetweenLists(UserData.i, CardUUID.s, FromList.s, ToList.s)
    
    *This.Private_Members = UserData
    
    *This\Project\MoveCardBetweenList(CardUUID, FromList, ToList)
    
  EndProcedure
  
  ; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  ; <<<<< The Window size change manager <<<<<  
  
  Procedure MainWindowSizeChangeManager(*This.Private_Members)
    
    Width.i = WindowWidth(#MainWindow)
    Height.i = WindowHeight(#MainWindow)
    CanvasWidth.i = *This\MainBoard\ComputeBoardCanvasWidth()
    
    *This\MainWindowSettings\SetIntegers("Width", Width)
    *This\MainWindowSettings\SetIntegers("Height", Height)
    
    MoveButtonImageGroup(#ButtonNew, #ButtonTrash, Width - 55, 5, 5)
    
    ResizeGadget(#ScrollAreaBoard, #PB_Ignore, #PB_Ignore, Width-65, Height-10)
    ResizeGadget(#CanvasBoard, #PB_Ignore, #PB_Ignore, CanvasWidth, Height)
    *This\MainBoard\DrawEverything()
    
  EndProcedure
  
  ; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  ; <<<<< Create the new project window <<<<<
  
  Procedure CreateNewProjectWindow(*This.Private_Members)
    
    If OpenWindow(#NewProjectWindow, 0, 0, 400, 80, *This\Language\Message(Language::#NEW_PROJECT), #PB_Window_SystemMenu|#PB_Window_WindowCentered, WindowID(#MainWindow))
      TextGadget(#TextNewNewProjectName, 5, 5, 150, 30, *This\Language\Message(Language::#PROJECT_NAME))
      StringGadget(#StringNewNewProjectName, 160, 5, 400 - 165, 30, "")    
      ButtonGadget(#ButtonNewProjectCreate, 400 - 210 , 40, 100, 34, *This\Language\Message(Language::#BUTTON_CREATE))
      ButtonGadget(#ButtonNewProjectCancel, 400 - 105, 40, 100, 34, *This\Language\Message(Language::#BUTTON_CANCEL))
    EndIf
    
  EndProcedure
  
  Procedure ButtonNewProjectCreateHandler(*This.Private_Members)
    
    ProjectName.s = GetGadgetText(#StringNewNewProjectName)
    
    If ProjectName <> ""
      
      If *This\Project\GetProjectFileLoaded() = #True
        *This\Project\XML_CreateFile()
      EndIf
      
      *This\Project\Refresh()
      *This\MainBoard\ClearBoardCards()
      
      *This\Project\SetName(ProjectName)
      *This\Project\SetProjectFileName(*This\UserPath + ProjectName + ".dbp")
      *This\Project\SetProjectFileLoaded(#True)
      Project_To_GUI(*This)
      
    EndIf
    
  EndProcedure
  
  Procedure OpenProjectButtonHandler(*This.Private_Members)
    
    Title.s = *This\Language\Message(Language::#OPEN_PROJECT_REQUESTER_TITLE)
    FileFilter.s = *This\Language\Message(Language::#PROJECT_FILE_FILTER)
    ProjectFileName.s = OpenFileRequester(Title, *This\UserPath, FileFilter, 0, 0, WindowID(#MainWindow))
    
    If ProjectFileName <> ""
      *This\Project\SetProjectFileName(ProjectFileName)
      *This\Project\SetProjectFileLoaded(#True)
      *This\Project\XML_LoadFile()
      *This\Project\SanityCheck(*This\GeneralSettings\GetDeltaTime())
      Project_To_GUI(*This)
    EndIf
    
  EndProcedure
  
  Procedure SaveProjectButtonHandler(*This.Private_Members)
    
    If *This\Project\GetProjectFileLoaded() = #True
      *This\Project\XML_CreateFile()
    EndIf
    
  EndProcedure
  
  Procedure AddCardWindow(*This.Private_Members)
    
    If *This\Project\GetProjectFileLoaded() = #True
      
      If OpenWindow(#AddCardWindow, 0, 0, 400, 435, *This\Language\Message(Language::#ADD_CARD_DIALOG_TITLE), #PB_Window_SystemMenu|#PB_Window_WindowCentered, WindowID(#MainWindow))
        
        TextGadget(#TextAddCardCardTitle, 5, 5, 150, 30, *This\Language\Message(Language::#ADD_EDIT_CARD_CARD_TITLE))
        StringGadget(#StringAddCardCardTitle, 160, 5, 400 - 165, 34, "") 
        
        TextGadget(#TextAddCardCardDescription, 5, 45, 390, 30, *This\Language\Message(Language::#ADD_EDIT_CARD_CARD_DESCRIPTION), #PB_Text_Center)
        
        EditorGadget(#EditorAddCardCardDescription, 5, 75, 390, 250, #PB_Editor_WordWrap)
        
        OptionGadget(#OptionAddCardToIdeas, 5, 330, 190, 30, *This\Language\Message(Language::#BOARD_IDEAS_TODO))
        OptionGadget(#OptionAddCardToInProgress, 195, 330, 190, 30, *This\Language\Message(Language::#BOARD_IN_PROGRESS))
        OptionGadget(#OptionAddCardToCompleted, 5, 365, 190, 30, *This\Language\Message(Language::#BOARD_COMPLETED))
        OptionGadget(#OptionAddCardToAbandoned, 195, 365, 190, 30, *This\Language\Message(Language::#BOARD_ABANDONED))
        
        Select *This\MainBoard\GetSelectedBoardName()
            
          Case "Ideas"
            SetGadgetState(#OptionAddCardToIdeas, #True)
            
          Case "InProgress"
            SetGadgetState(#OptionAddCardToInProgress, #True)
            
          Case "Completed"
            SetGadgetState(#OptionAddCardToCompleted, #True)
            
          Case "Abandoned"
            SetGadgetState(#OptionAddCardToAbandoned, #True)
            
          Default
            SetGadgetState(#OptionAddCardToIdeas, #True)
            
        EndSelect
        
        ButtonGadget(#ButtonAddCardCreate, 400 - 210 , 395, 100, 34, *This\Language\Message(Language::#BUTTON_ADD))
        ButtonGadget(#ButtonAddCardCancel, 400 - 105, 395, 100, 34, *This\Language\Message(Language::#BUTTON_CANCEL))
        
      EndIf
      
    EndIf
    
  EndProcedure
  
  Procedure ButtonAddCardHandler(*This.Private_Members)
    
    UUID.S = GenerateUUID()
    CreationDate.l = Date()
    Title.s = GetGadgetText(#StringAddCardCardTitle)
    Description.s = GetGadgetText(#EditorAddCardCardDescription)
    
    If GetGadgetState(#OptionAddCardToIdeas) = #True
      *This\MainBoard\AddBoardCard("Ideas", Title, Description, UUID)
      *This\Project\SelectCardsListByName("Ideas")
      *ListOfCardsList.CardsList::CardsList = *This\Project\GetListOfCardsList()
      *ListOfCardsList\AddCardsEx(Card::New(Title, Description, UUID, CreationDate))
    EndIf
    
    If GetGadgetState(#OptionAddCardToInProgress) = #True
      *This\MainBoard\AddBoardCard("InProgress", Title, Description, UUID)
      *This\Project\SelectCardsListByName("InProgress")
      *ListOfCardsList.CardsList::CardsList = *This\Project\GetListOfCardsList()
      *ListOfCardsList\AddCardsEx(Card::New(Title, Description, UUID, CreationDate))
    EndIf
    
    If GetGadgetState(#OptionAddCardToCompleted) = #True
      *This\MainBoard\AddBoardCard("Completed", Title, Description, UUID)
      *This\Project\SelectCardsListByName("Completed")
      *ListOfCardsList.CardsList::CardsList = *This\Project\GetListOfCardsList()
      *ListOfCardsList\AddCardsEx(Card::New(Title, Description, UUID, CreationDate, CreationDate))
    EndIf
    
    If GetGadgetState(#OptionAddCardToAbandoned) = #True
      *This\MainBoard\AddBoardCard("Abandoned", Title, Description, UUID)
      *This\Project\SelectCardsListByName("Abandoned")
      *ListOfCardsList.CardsList::CardsList = *This\Project\GetListOfCardsList()
      *ListOfCardsList\AddCardsEx(Card::New(Title, Description, UUID, CreationDate, 0, CreationDate))
    EndIf
    
  EndProcedure
  
  Procedure EditCardWindow(*This.Private_Members)
    
    If *This\Project\GetProjectFileLoaded() = #True
      
      BoardName.s = *This\MainBoard\GetSelectedBoardName()
      
      If BoardName <> ""
        
        Protected UUID.String, Title.String, Description.String
        
        *This\MainBoard\GetSelectedCardInfo(UUID, Title, Description)
        
        If UUID\s <> ""
          
          If OpenWindow(#EditCardWindow, 0, 0, 400, 385, *This\Language\Message(Language::#EDIT_CARD_DIALOG_TITLE), #PB_Window_SystemMenu|#PB_Window_WindowCentered, WindowID(#MainWindow))
            
            TextGadget(#TextEditCardCardTitle, 5, 5, 150, 30, *This\Language\Message(Language::#ADD_EDIT_CARD_CARD_TITLE))
            StringGadget(#StringEditCardCardTitle, 160, 5, 400 - 165, 34, Title\s) 
            
            TextGadget(#TextEditCardCardDescription, 5, 45, 390, 30, *This\Language\Message(Language::#ADD_EDIT_CARD_CARD_DESCRIPTION), #PB_Text_Center)
            
            EditorGadget(#EditorEditCardCardDescription, 5, 75, 390, 265, #PB_Editor_WordWrap)
            SetGadgetText(#EditorEditCardCardDescription, Description\s)
            
            ButtonGadget(#ButtonEditCardOK, 400 - 210 , 345, 100, 34, *This\Language\Message(Language::#BUTTON_OK))
            ButtonGadget(#ButtonEditCardCancel, 400 - 105, 345, 100, 34, *This\Language\Message(Language::#BUTTON_CANCEL))
            
          EndIf
          
        EndIf
        
        
      EndIf
      
    EndIf
    
  EndProcedure
  
  Procedure ButtonEditCardOkHandler(*This.Private_Members)
    
    If *This\Project\GetProjectFileLoaded() = #True
      
      BoardName.s = *This\MainBoard\GetSelectedBoardName()
      
      If BoardName <> ""
        
        Protected UUID.String
        
        *This\MainBoard\GetSelectedCardInfo(UUID, #Null, #Null)
        
        If UUID\s <> ""
          
          Title.s = GetGadgetText(#StringEditCardCardTitle)
          Description.s = GetGadgetText(#EditorEditCardCardDescription)
          
          *This\MainBoard\UpdateBoardCard(BoardName, UUID\s, Title, Description)
          *This\Project\SelectCardsListByName(BoardName)
          
          *ListOfCardsList.CardsList::CardsList = *This\Project\GetListOfCardsList()
          *ListOfCardsList\ResetCards()
          
          While *ListOfCardsList\NextCards()
            
            *Card.Card::Card = *ListOfCardsList\GetCards()
            
            If *Card\GetUUID() = UUID\s
              *Card\SetTitle(Title)
              *Card\SetDescription(Description)
              Break
            EndIf
            
          Wend
          
        EndIf
        
      EndIf
      
    EndIf    
    
  EndProcedure
  
  Procedure RemoveCardButtonHandler(*This.Private_Members)
    
    If *This\Project\GetProjectFileLoaded() = #True
      
      BoardName.s = *This\MainBoard\GetSelectedBoardName()
      
      If BoardName <> ""
        
        Protected UUID.String, CardTitle.String
        
        *This\MainBoard\GetSelectedCardInfo(UUID, CardTitle, #Null)
        
        If UUID\s <> ""
          
          Title.s = *This\Language\Message(Language::#WARNING_REQUESTER_TITLE)
          Message.s = ReplaceString(*This\Language\Message(Language::#ASK_SEND_TO_TRASH), "%CARD_TITLE%", CardTitle\s)
          
          If MessageRequester(Title, Message, #PB_MessageRequester_YesNo, WindowID(#MainWindow)) = #PB_MessageRequester_Yes
            
            *This\MainBoard\DeleteBoardCard(BoardName, UUID\s)
            *This\Project\MoveCardBetweenList(UUID\s, BoardName, "Trash")
            
            *This\Project\SelectCardsListByName("Trash")
            
            *ListOfCardsList.CardsList::CardsList = *This\Project\GetListOfCardsList()
            
            If *ListOfCardsList\CardsSize() >= 1
              *This\TrashButtonCtrl\SetStatus(1)
            Else
              *This\TrashButtonCtrl\SetStatus(0)
            EndIf
            
          EndIf
          
        EndIf
        
      EndIf
      
    EndIf  
    
  EndProcedure
  
  Procedure MoveCardButtonHandler(*This.Private_Members)
    
    If *This\Project\GetProjectFileLoaded() = #True
      
      BoardName.s = *This\MainBoard\GetSelectedBoardName()
      
      If BoardName <> ""
        
        Select BoardName
            
          Case "Ideas"
            DestinationA.s = *This\Language\Message(Language::#BOARD_IN_PROGRESS)
            DestinationB.s = *This\Language\Message(Language::#BOARD_COMPLETED)
            DestinationC.s = *This\Language\Message(Language::#BOARD_ABANDONED)
            
          Case "InProgress"
            DestinationA = *This\Language\Message(Language::#BOARD_IDEAS_TODO)
            DestinationB = *This\Language\Message(Language::#BOARD_COMPLETED)
            DestinationC = *This\Language\Message(Language::#BOARD_ABANDONED)
            
          Case "Completed"
            DestinationA = *This\Language\Message(Language::#BOARD_IDEAS_TODO)
            DestinationB = *This\Language\Message(Language::#BOARD_IN_PROGRESS)
            DestinationC = *This\Language\Message(Language::#BOARD_ABANDONED)
            
          Case "Abandoned"  
            DestinationA = *This\Language\Message(Language::#BOARD_IDEAS_TODO)
            DestinationB = *This\Language\Message(Language::#BOARD_IN_PROGRESS)
            DestinationC = *This\Language\Message(Language::#BOARD_COMPLETED)
            
        EndSelect
        
        If OpenWindow(#MoveCardWindow, 0, 0, 300, 140, *This\Language\Message(Language::#MOVE_CARD_DIALOG_TITLE), #PB_Window_SystemMenu|#PB_Window_WindowCentered, WindowID(#MainWindow))
          
          OptionGadget(#OptionMoveCardDestinationA, 5, 5, 190, 30, DestinationA)
          OptionGadget(#OptionMoveCardDestinationB, 5, 35, 190, 30, DestinationB)
          OptionGadget(#OptionMoveCardDestinationC, 5, 65, 190, 30, DestinationC)
          
          ButtonGadget(#ButtonMoveCardOK, 300 - 210 , 100, 100, 34, *This\Language\Message(Language::#BUTTON_OK))
          ButtonGadget(#ButtonMoveCardCancel, 300 - 105, 100, 100, 34, *This\Language\Message(Language::#BUTTON_CANCEL))
          
        EndIf
        
      EndIf
      
    EndIf
    
  EndProcedure
  
  Procedure ButtonMoveCardOkHandler(*This.Private_Members)
    
    If *This\Project\GetProjectFileLoaded() = #True
      
      BoardName.s = *This\MainBoard\GetSelectedBoardName()
      
      If BoardName <> ""
        
        Select BoardName
            
          Case "Ideas"
            Destination00.s = "InProgress"
            Destination01.s = "Completed"
            Destination02.s = "Abandoned"
            
          Case "InProgress"
            Destination00.s = "Ideas"
            Destination01.s = "Completed"
            Destination02.s = "Abandoned"
            
          Case "Completed"
            Destination00.s = "Ideas"
            Destination01.s = "InProgress"
            Destination02.s = "Abandoned"
            
          Case "Abandoned"  
            Destination00.s = "Ideas"
            Destination01.s = "InProgress"
            Destination02.s = "Completed"
            
        EndSelect
        
        Protected CardUUID.String, CardTitle.String, CardDescription.String
        
        *This\MainBoard\GetSelectedCardInfo(CardUUID, CardTitle, CardDescription)
        
        If GetGadgetState(#OptionMoveCardDestinationA) = #True
          *This\MainBoard\DeleteBoardCard(BoardName, CardUUID\s)
          *This\Project\MoveCardBetweenList(CardUUID\s, BoardName, Destination00)
          *This\MainBoard\AddBoardCard(Destination00, CardTitle\s, CardDescription\s, CardUUID\s)
        EndIf
        
        If GetGadgetState(#OptionMoveCardDestinationB) = #True
          *This\MainBoard\DeleteBoardCard(BoardName, CardUUID\s)
          *This\Project\MoveCardBetweenList(CardUUID\s, BoardName, Destination01)
          *This\MainBoard\AddBoardCard(Destination01, CardTitle\s, CardDescription\s, CardUUID\s)
        EndIf
        
        If GetGadgetState(#OptionMoveCardDestinationC) = #True
          *This\MainBoard\DeleteBoardCard(BoardName, CardUUID\s)
          *This\Project\MoveCardBetweenList(CardUUID\s, BoardName, Destination02)
          *This\MainBoard\AddBoardCard(Destination02, CardTitle\s, CardDescription\s, CardUUID\s)
        EndIf
        
      EndIf
      
    EndIf
    
  EndProcedure
  
  Procedure AskNewFont(*This.Private_Members)
    
    If FontRequester(*This\GeneralSettings\GetFontName(), *This\GeneralSettings\GetFontSize(), 0, 0, 0, WindowID(#OptionsSettingsWindow))
      
      *This\GeneralSettings\SetFontName(SelectedFontName())
      *This\GeneralSettings\SetFontSize(SelectedFontSize())
      SetGadgetText(#StringFontName, *This\GeneralSettings\GetFontName())
      SetGadgetText(#StringFontSize, Str(*This\GeneralSettings\GetFontSize()))
      
    EndIf 
    
  EndProcedure 
  
  Procedure AskNewColor(*This.Private_Members, GadgetID)
    
    Select GadgetID
        
      Case #ColorPreviewBorderColor
        CurrentColor.l = RGB(Red(*This\GeneralSettings\GetBorderColor()), Green(*This\GeneralSettings\GetBorderColor()), Blue(*This\GeneralSettings\GetBorderColor()))
        
      Case #ColorPreviewListBackColor
        CurrentColor = RGB(Red(*This\GeneralSettings\GetListBackColor()), Green(*This\GeneralSettings\GetListBackColor()), Blue(*This\GeneralSettings\GetListBackColor()))
        
      Case #ColorPreviewCardBackColor
        CurrentColor = RGB(Red(*This\GeneralSettings\GetCardBackColor()), Green(*This\GeneralSettings\GetCardBackColor()), Blue(*This\GeneralSettings\GetCardBackColor()))
        
      Case #ColorPreviewTextColor
        CurrentColor = RGB(Red(*This\GeneralSettings\GetTextColor()), Green(*This\GeneralSettings\GetTextColor()), Blue(*This\GeneralSettings\GetTextColor()))
        
      Case #ColorPreviewSelectedBorderColor
        CurrentColor = RGB(Red(*This\GeneralSettings\GetSelectedBorderColor()), Green(*This\GeneralSettings\GetSelectedBorderColor()), Blue(*This\GeneralSettings\GetSelectedBorderColor()))
        
      Case #ColorPreviewFlyOverBorderColor
        CurrentColor = RGB(Red(*This\GeneralSettings\GetFlyOverBorderColor()), Green(*This\GeneralSettings\GetFlyOverBorderColor()), Blue(*This\GeneralSettings\GetFlyOverBorderColor()))
        
    EndSelect 
    
    NewColor.l = ColorRequester(CurrentColor, WindowID(#OptionsSettingsWindow))
    
    If NewColor > -1
      ColorPreview::SetCurrentColor(GadgetID, NewColor)
    EndIf
    
  EndProcedure
  
  Procedure OptionsSettingsWindow(*This.Private_Members)
    
    If OpenWindow(#OptionsSettingsWindow, 0, 0, 400, 580, *This\Language\Message(Language::#OPTIONS_SETTINGS_DIALOG_TITLE), #PB_Window_SystemMenu|#PB_Window_WindowCentered, WindowID(#MainWindow))
      
      FrameGadget(#FrameChooseLanguage, 5, 5, 390, 150, *This\Language\Message(Language::#OPTIONS_SETTINGS_CHOOSE_LANGUAGE))
      ListViewGadget(#ListViewChooseLanguage, 10, 30, 380, 120)
      
      If ExamineDirectory(0, *This\Language\GetPath(), "*.xml") <> 0
        
        LanguageIndex.i = 0
        
        While NextDirectoryEntry(0) <> 0
          
          If DirectoryEntryType(0) = #PB_DirectoryEntry_File
            
            Language.s = DirectoryEntryName(0)
            
            If Left(Language, 1) <> "." And Left(Language, 1) <> ".."
              
              AddGadgetItem(#ListViewChooseLanguage, -1, StringField(GetFilePart(Language), 1, "."))
              
              If StringField(GetFilePart(Language), 1, ".") = *This\Language\GetLanguageName()
                CurrentLanguageIndex.i = LanguageIndex
              EndIf
              
              LanguageIndex + 1
              
            EndIf
            
          EndIf
          
        Wend
        
        SetGadgetItemState(#ListViewChooseLanguage, CurrentLanguageIndex, #True)
        
        FinishDirectory(0)
        
      EndIf
      
      FrameGadget(#FrameFontColor, 5, 160, 390, 315, *This\Language\Message(Language::#OPTIONS_SETTINGS_FONT_COLORS))   
      TextGadget(#TextFontName, 10, 190, 175, 30, *This\Language\Message(Language::#OPTIONS_SETTINGS_FONT_NAME), #PB_Text_Center)  
      StringGadget(#StringFontName, 240, 190, 100, 30, *This\GeneralSettings\GetFontName(), #PB_String_ReadOnly)
      ButtonGadget(#ButtonChooseFont, 345, 190, 40, 30, "...")
      TextGadget(#TextFontSize, 10, 225, 175, 30, *This\Language\Message(Language::#OPTIONS_SETTINGS_FONT_SIZE), #PB_Text_Center)  
      StringGadget(#StringFontSize, 240, 225, 100, 30, Str(*This\GeneralSettings\GetFontSize()), #PB_String_ReadOnly)
      
      TextGadget(#TextBorderColor, 10, 260, 250, 30, *This\Language\Message(Language::#OPTIONS_SETTINGS_BORDER_COLOR), #PB_Text_Center)
      
      BorderColorRGB.l = RGB(Red(*This\GeneralSettings\GetBorderColor()), Green(*This\GeneralSettings\GetBorderColor()), Blue(*This\GeneralSettings\GetBorderColor()))
      ColorPreview::Gadget(#ColorPreviewBorderColor, 345, 260, 40, 30, BorderColorRGB, #False)
      
      TextGadget(#TextListBackColor, 10, 295, 250, 30, *This\Language\Message(Language::#OPTIONS_SETTINGS_LIST_BACK_COLOR), #PB_Text_Center)
      ListBackColorRGB.l = RGB(Red(*This\GeneralSettings\GetListBackColor()), Green(*This\GeneralSettings\GetListBackColor()), Blue(*This\GeneralSettings\GetListBackColor()))
      ColorPreview::Gadget(#ColorPreviewListBackColor, 345, 295, 40, 30, ListBackColorRGB, #False)
      
      TextGadget(#TextCardBackColor, 10, 330, 250, 30, *This\Language\Message(Language::#OPTIONS_SETTINGS_CARD_BACK_COLOR), #PB_Text_Center)
      CardBackColorRGB.l = RGB(Red(*This\GeneralSettings\GetCardBackColor()), Green(*This\GeneralSettings\GetCardBackColor()), Blue(*This\GeneralSettings\GetCardBackColor()))
      ColorPreview::Gadget(#ColorPreviewCardBackColor, 345, 330, 40, 30, CardBackColorRGB, #False)
      
      TextGadget(#TextTextColor, 10, 365, 250, 30, *This\Language\Message(Language::#OPTIONS_SETTINGS_TEXT_COLOR), #PB_Text_Center)
      TextColorRGB.l = RGB(Red(*This\GeneralSettings\GetTextColor()), Green(*This\GeneralSettings\GetTextColor()), Blue(*This\GeneralSettings\GetTextColor()))
      ColorPreview::Gadget(#ColorPreviewTextColor, 345, 365, 40, 30, TextColorRGB, #False)
      
      TextGadget(#TextSelectedBorderColor, 10, 400, 250, 30, *This\Language\Message(Language::#OPTIONS_SETTINGS_SELECTED_BORDER_COLOR), #PB_Text_Center)
      SelectedBorderColorRGB.l = RGB(Red(*This\GeneralSettings\GetSelectedBorderColor()), Green(*This\GeneralSettings\GetSelectedBorderColor()), Blue(*This\GeneralSettings\GetSelectedBorderColor()))
      ColorPreview::Gadget(#ColorPreviewSelectedBorderColor, 345, 400, 40, 30, SelectedBorderColorRGB, #False)
      
      TextGadget(#TextFlyOverBorderColor, 10, 435, 250, 30, *This\Language\Message(Language::#OPTIONS_SETTINGS_FLYOVER_BORDER_COLOR), #PB_Text_Center)
      FlyOverBorderColorRGB.l = RGB(Red(*This\GeneralSettings\GetFlyOverBorderColor()), Green(*This\GeneralSettings\GetFlyOverBorderColor()), Blue(*This\GeneralSettings\GetFlyOverBorderColor()))
      ColorPreview::Gadget(#ColorPreviewFlyOverBorderColor, 345, 435, 40, 30, FlyOverBorderColorRGB, #False)
 
      FrameGadget(#FrameMoveCard, 5, 480, 390, 55, *This\Language\Message(Language::#OPTIONS_SETTINGS_AUTOMATIC_CARD_MOVE))   
      OptionGadget(#OptionMoveIn30Days, 10, 500, 120, 30, *This\Language\Message(Language::#OPTIONS_SETTINGS_30_DAYS))
      OptionGadget(#OptionMoveIn60Days, 135, 500, 120, 30, *This\Language\Message(Language::#OPTIONS_SETTINGS_60_DAYS))
      OptionGadget(#OptionMoveIn90Days, 260, 500, 120, 30, *This\Language\Message(Language::#OPTIONS_SETTINGS_90_DAYS))
      
      Select *This\GeneralSettings\GetDeltaTimeSetting()
          
        Case Setting::#DeltaTimeSetting_30_Days 
          SetGadgetState(#OptionMoveIn30Days, #True)
          
        Case Setting::#DeltaTimeSetting_60_Days 
          SetGadgetState(#OptionMoveIn60Days, #True)
          
        Case Setting::#DeltaTimeSetting_90_Days
          SetGadgetState(#OptionMoveIn90Days, #True)
          
      EndSelect
      
      ButtonGadget(#ButtonOptionsSettingsOK, 400 - 210, 540, 100, 34, *This\Language\Message(Language::#BUTTON_OK))
      ButtonGadget(#ButtonOptionsSettingsCancel, 400 - 105, 540, 100, 34, *This\Language\Message(Language::#BUTTON_CANCEL))
      
    EndIf
    
  EndProcedure
  
  Procedure OptionsSettingsOK(*This.Private_Members)
    
    SelectedLanguage.s = GetGadgetText(#ListViewChooseLanguage)
    
    If SelectedLanguage <> *This\Language\GetLanguageName()
      *This\Language\SetLanguageName(SelectedLanguage)
      *This\Language\LoadFile()
      Language_To_GUI(*This)
    EndIf
    
    BoarderColor.l = ColorPreview::GetCurrentColor(#ColorPreviewBorderColor)
    *This\GeneralSettings\SetBorderColor(RGBA(Red(BoarderColor), Green(BoarderColor), Blue(BoarderColor), 255))
          
    ListBackColor.l = ColorPreview::GetCurrentColor(#ColorPreviewListBackColor)
    *This\GeneralSettings\SetListBackColor(RGBA(Red(ListBackColor), Green(ListBackColor), Blue(ListBackColor), 255))
    
    CardBackColor.q = ColorPreview::GetCurrentColor(#ColorPreviewCardBackColor)
    *This\GeneralSettings\SetCardBackColor(RGBA(Red(CardBackColor), Green(CardBackColor), Blue(CardBackColor), 255))
    
    TextColor.l = ColorPreview::GetCurrentColor(#ColorPreviewTextColor)
    *This\GeneralSettings\SetTextColor(RGBA(Red(TextColor), Green(TextColor), Blue(TextColor), 255))
    
    SelectedBorderColor.l = ColorPreview::GetCurrentColor(#ColorPreviewSelectedBorderColor)
    *This\GeneralSettings\SetSelectedBorderColor(RGBA(Red(SelectedBorderColor), Green(SelectedBorderColor), Blue(SelectedBorderColor), 255))
    
    FlyOverBorderColor.l = ColorPreview::GetCurrentColor(#ColorPreviewFlyOverBorderColor)
    *This\GeneralSettings\SetFlyOverBorderColor(RGBA(Red(FlyOverBorderColor), Green(FlyOverBorderColor), Blue(FlyOverBorderColor), 255))
    
    If GetGadgetState(#OptionMoveIn30Days) = #True
      *This\GeneralSettings\SetDeltaTimeSetting(Setting::#DeltaTimeSetting_30_Days)
    EndIf
    
    If GetGadgetState(#OptionMoveIn60Days) = #True
      *This\GeneralSettings\SetDeltaTimeSetting(Setting::#DeltaTimeSetting_60_Days)
    EndIf
    
    If GetGadgetState(#OptionMoveIn90Days) = #True
      *This\GeneralSettings\SetDeltaTimeSetting(Setting::#DeltaTimeSetting_90_Days)
    EndIf
    
  EndProcedure
  
  
  Procedure CloseOptionsSettings()
    
    ColorPreview::Free(#ColorPreviewBorderColor)
    ColorPreview::Free(#ColorPreviewListBackColor)
    ColorPreview::Free(#ColorPreviewCardBackColor)
    ColorPreview::Free(#ColorPreviewTextColor)
    ColorPreview::Free(#ColorPreviewSelectedBorderColor)
    ColorPreview::Free(#ColorPreviewFlyOverBorderColor)
    CloseWindow(#OptionsSettingsWindow)
    
  EndProcedure
  
  
  Procedure ArchivesManagerWindow(*This.Private_Members)
    
    If *This\ArchiveButtonCtrl\GetStatus() = 1
      
      If OpenWindow(#ArchiveWindow, 0, 0, 650, 500, *This\Language\Message(Language::#ARCHIVE_MANAGER_DIALOG_TITLE), #PB_Window_SystemMenu|#PB_Window_WindowCentered, WindowID(#MainWindow))
        
        CanvasWidth.i = *This\ArchiveBoard\ComputeBoardCanvasWidth()
        
        ScrollAreaGadget(#ScrollAreaArchiveBoard, 5, 5, 650-160, 490, CanvasWidth, 850, 30, #PB_ScrollArea_Flat)
          CanvasGadget(#CanvasArchiveBoard, 0, 0, CanvasWidth, 800, #PB_Canvas_Border)
        CloseGadgetList() 
        
        *This\ArchiveBoard\SetBoardDisplayName("Archive", *This\Language\Message(Language::#BOARD_ARCHIVE))
        
        ButtonGadget(#ButtonEmptyArchive, 650-150, 5, 145, 34, *This\Language\Message(Language::#ARCHIVE_MANAGER_EMPTY_THE_ARCHIVE))
        ButtonGadget(#ButtonDeleteCardFromArchive, 650-150, 45, 145, 34, *This\Language\Message(Language::#ARCHIVE_TRASH_MANAGER_DELETE_CARD))
        ButtonGadget(#ButtonRestoreCardFromArchive, 650-150, 90, 145, 34, *This\Language\Message(Language::#ARCHIVE_MANAGER_UNARCHIVE_CARD))
        ButtonGadget(#ButtonCloseArchiveManager, 650-150, 460, 145, 34, *This\Language\Message(Language::#BUTTON_CLOSE))
        
        *This\Project\SelectCardsListByName("Archive")
        *ListOfCardsList.CardsList::CardsList = *This\Project\GetListOfCardsList()
        *ListOfCardsList\ResetCards()
        
        While *ListOfCardsList\NextCards()
          *Card.Card::Card = *ListOfCardsList\GetCards()
          *This\ArchiveBoard\AddBoardCard("Archive", *Card\GetTitle(), *Card\GetDescription(), *Card\GetUUID())
        Wend
        
        *This\ArchiveBoard\DrawEverything()
        
      EndIf
      
    EndIf
    
  EndProcedure
  
  Procedure EmptyArchiveButtonHandler(*This.Private_Members)
    
    Title.s = *This\Language\Message(Language::#WARNING_REQUESTER_TITLE)
    Message.s = *This\Language\Message(Language::#ASK_EMPTY_ARCHIVE)
    
    If MessageRequester(Title, Message, #PB_MessageRequester_YesNo, WindowID(#ArchiveWindow)) = #PB_MessageRequester_Yes
      *This\Project\ClearAllCardsFromList("Archive")
      *This\ArchiveBoard\ClearBoardCards()
      *This\ArchiveBoard\DrawEverything()
      *This\ArchiveButtonCtrl\SetStatus(0)
    EndIf
    
  EndProcedure
  
  Procedure DeleteCardFromArchiveButtonHandler(*This.Private_Members)
    
    BoardName.s = *This\ArchiveBoard\GetSelectedBoardName()
    
    If BoardName <> ""
      
      Protected UUID.String, CardTitle.String
      
      *This\ArchiveBoard\GetSelectedCardInfo(UUID, CardTitle, #Null)
      
      If UUID\s <> ""
        
        Title.s = *This\Language\Message(Language::#WARNING_REQUESTER_TITLE)
        Message.s = ReplaceString(*This\Language\Message(Language::#ASK_DELETE_CARD_FROM_ARCHIVE), "%CARD_TITLE%", CardTitle\s)
        
        If MessageRequester(Title, Message, #PB_MessageRequester_YesNo, WindowID(#ArchiveWindow)) = #PB_MessageRequester_Yes
          
          *This\Project\DeleteCardFromList("Archive", UUID\s)
          *This\ArchiveBoard\DeleteBoardCard("Archive", UUID\s)
          *This\ArchiveBoard\DrawEverything()
          
          *This\Project\SelectCardsListByName("Archive")
          *ListOfCardsList.CardsList::CardsList = *This\Project\GetListOfCardsList()
          
          If *ListOfCardsList\CardsSize() >= 1
            *This\ArchiveButtonCtrl\SetStatus(1)
          Else
            *This\ArchiveButtonCtrl\SetStatus(0)
          EndIf
          
        EndIf
        
      EndIf
      
    EndIf
    
  EndProcedure
  
  Procedure UnarchiveCardFromTheArchiveButtonHandler(*This.Private_Members)
    
    BoardName.s = *This\ArchiveBoard\GetSelectedBoardName()
    
    If BoardName <> ""
      
      Protected UUID.String, CardTitle.String, CardDescription.String
      
      *This\ArchiveBoard\GetSelectedCardInfo(UUID, CardTitle, CardDescription)
      
      If UUID\s <> ""
        
        *This\Project\MoveCardBetweenList(UUID\s, "Archive", "Completed")
        *This\MainBoard\AddBoardCard("Completed", CardTitle\s, CardDescription\s, UUID\s)
        *This\MainBoard\DrawEverything()
        *This\ArchiveBoard\DeleteBoardCard("Archive", UUID\s)
        *This\ArchiveBoard\DrawEverything()
        *This\Project\SelectCardsListByName("Archive")
        *ListOfCardsList.CardsList::CardsList = *This\Project\GetListOfCardsList()
        
        If *ListOfCardsList\CardsSize() >= 1
          *This\ArchiveButtonCtrl\SetStatus(1)
        Else
          *This\ArchiveButtonCtrl\SetStatus(0)
        EndIf
        
      EndIf
      
    EndIf
    
  EndProcedure
  
  Procedure CloseArchiveManager(*This.Private_Members)
    
    *This\ArchiveBoard\ClearBoardCards()
    CloseWindow(#ArchiveWindow)
    
  EndProcedure
  
  
  Procedure TrashManagerWindow(*This.Private_Members)
    
    If *This\TrashButtonCtrl\GetStatus() = 1
      
      If OpenWindow(#TrashWindow, 0, 0, 650, 500, *This\Language\Message(Language::#TRASH_MANAGER_DIALOG_TITLE), #PB_Window_SystemMenu|#PB_Window_WindowCentered, WindowID(#MainWindow))
        
        CanvasWidth.i = *This\TrashBoard\ComputeBoardCanvasWidth()
        
        ScrollAreaGadget(#ScrollAreaTrashBoard, 5, 5, 650-160, 490, CanvasWidth, 850, 30, #PB_ScrollArea_Flat)
          CanvasGadget(#CanvasTrashBoard, 0, 0, CanvasWidth, 800, #PB_Canvas_Border)
        CloseGadgetList() 
        
        *This\TrashBoard\SetBoardDisplayName("Trash", *This\Language\Message(Language::#BOARD_TRASH))
        
        ButtonGadget(#ButtonEmptyTrash, 650-150, 5, 145, 34, *This\Language\Message(Language::#TRASH_MANAGER_EMPTY_THE_TRASH))
        ButtonGadget(#ButtonDeleteCardFromTrash, 650-150, 45, 145, 34, *This\Language\Message(Language::#ARCHIVE_TRASH_MANAGER_DELETE_CARD))
        ButtonGadget(#ButtonRestoreCardFromTrash, 650-150, 90, 145, 34, *This\Language\Message(Language::#TRASH_MANAGER_RESTORE_CARD))
        ButtonGadget(#ButtonCloseTrashManager, 650-150, 460, 145, 34, *This\Language\Message(Language::#BUTTON_CLOSE))
        
        *This\Project\SelectCardsListByName("Trash")
        *ListOfCardsList.CardsList::CardsList = *This\Project\GetListOfCardsList()
        *ListOfCardsList\ResetCards()
        
        While *ListOfCardsList\NextCards()
          *Card.Card::Card = *ListOfCardsList\GetCards()
          *This\TrashBoard\AddBoardCard("Trash", *Card\GetTitle(), *Card\GetDescription(), *Card\GetUUID())
        Wend
        
        *This\TrashBoard\DrawEverything()
        
      EndIf
      
    EndIf 
    
  EndProcedure
  
  Procedure EmptyTrashButtonHandler(*This.Private_Members)
    
    Title.s = *This\Language\Message(Language::#WARNING_REQUESTER_TITLE)
    Message.s = *This\Language\Message(Language::#ASK_EMPTY_TRASH)
    
    If MessageRequester(Title, Message, #PB_MessageRequester_YesNo, WindowID(#TrashWindow)) = #PB_MessageRequester_Yes
      *This\Project\ClearAllCardsFromList("Trash")
      *This\TrashBoard\ClearBoardCards()
      *This\TrashBoard\DrawEverything()
      *This\TrashButtonCtrl\SetStatus(0)
    EndIf
    
  EndProcedure
  
  Procedure DeleteCardFromTrashButtonHandler(*This.Private_Members)
    
    BoardName.s = *This\TrashBoard\GetSelectedBoardName()
    
    If BoardName <> ""
      
      Protected UUID.String, CardTitle.String
      
      *This\TrashBoard\GetSelectedCardInfo(UUID, CardTitle, #Null)
      
      If UUID\s <> ""
        
        Title.s = *This\Language\Message(Language::#WARNING_REQUESTER_TITLE)
        Message.s = ReplaceString(*This\Language\Message(Language::#ASK_DELETE_CARD_FROM_TRASH), "%CARD_TITLE%", CardTitle\s)
        
        If MessageRequester(Title, Message, #PB_MessageRequester_YesNo, WindowID(#TrashWindow)) = #PB_MessageRequester_Yes
          
          *This\Project\DeleteCardFromList("Trash", UUID\s)
          *This\TrashBoard\DeleteBoardCard("Trash", UUID\s)
          *This\TrashBoard\DrawEverything()
          
          *This\Project\SelectCardsListByName("Trash")
          *ListOfCardsList.CardsList::CardsList = *This\Project\GetListOfCardsList()
          
          If *ListOfCardsList\CardsSize() >= 1
            *This\TrashButtonCtrl\SetStatus(1)
          Else
            *This\TrashButtonCtrl\SetStatus(0)
          EndIf
          
        EndIf
        
      EndIf
      
    EndIf
    
  EndProcedure
  
  Procedure RestoreCardFromTheTrashButtonHandler(*This.Private_Members)
    
    BoardName.s = *This\TrashBoard\GetSelectedBoardName()
    
    If BoardName <> ""
      
      Protected UUID.String, CardTitle.String, CardDescription.String
      
      *This\TrashBoard\GetSelectedCardInfo(UUID, CardTitle, CardDescription)
      
      If UUID\s <> ""
        
        *This\Project\MoveCardBetweenList(UUID\s, "Trash", "Abandoned")
        *This\MainBoard\AddBoardCard("Abandoned", CardTitle\s, CardDescription\s, UUID\s)
        *This\MainBoard\DrawEverything()
        *This\TrashBoard\DeleteBoardCard("Trash", UUID\s)
        *This\TrashBoard\DrawEverything()
        *This\Project\SelectCardsListByName("Trash")
        *ListOfCardsList.CardsList::CardsList = *This\Project\GetListOfCardsList()
        
        If *ListOfCardsList\CardsSize() >= 1
          *This\TrashButtonCtrl\SetStatus(1)
        Else
          *This\TrashButtonCtrl\SetStatus(0)
        EndIf
        
      EndIf
      
    EndIf
    
  EndProcedure
  
  Procedure CloseTrashManager(*This.Private_Members)
    
    *This\TrashBoard\ClearBoardCards()
    CloseWindow(#TrashWindow)
    
  EndProcedure
  
  ; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  ; <<<<< Create the main window <<<<<
  
  Procedure CreateWindow(*This.Private_Members)
    
    X.i = *This\MainWindowSettings\GetIntegers("PosX")
    Y.i = *This\MainWindowSettings\GetIntegers("PosY")
    Width.i = *This\MainWindowSettings\GetIntegers("Width")
    Height.i = *This\MainWindowSettings\GetIntegers("Height")
    MinWidth.i = *This\MainWindowSettings\GetIntegers("MinWidth")
    MinHeight.i = *This\MainWindowSettings\GetIntegers("MinHeight")
    
    If OpenWindow(#MainWindow, X, Y, Width, Height, "", #PB_Window_MinimizeGadget | #PB_Window_MaximizeGadget | #PB_Window_SizeGadget)
      
      WindowBounds(#MainWindow, MinWidth, MinHeight, #PB_Default, #PB_Default)  
      
      CanvasWidth.i = *This\MainBoard\ComputeBoardCanvasWidth()
      
      ScrollAreaGadget(#ScrollAreaBoard, 5, 5, Width-65, Height-10, CanvasWidth, Height, 30, #PB_ScrollArea_Flat)
        CanvasGadget(#CanvasBoard, 0, 0, CanvasWidth, Height, #PB_Canvas_Border)
      CloseGadgetList() 
      
      ButtonImageGroup(#ButtonNew, #ButtonTrash, Width - 55, 5, 50, 50, 5)
      *This\ArchiveButtonCtrl\SetStatus(0)
      *This\TrashButtonCtrl\SetStatus(0)
      
      Language_To_GUI(*This)
      *This\MainBoard\DrawEverything()
      
    EndIf
    
  EndProcedure
  
  ; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  ; <<<<< The event manager <<<<<
  
  Procedure EventManager(*This.Private_Members)
    
    Repeat
      
      Select WaitWindowEvent()
          
        Case #PB_Event_Gadget
          
          Select EventGadget()
              
            Case #CanvasBoard
              *This\MainBoard\RefreshFlyingOverState()
              
              Select EventType()
                  
                Case #PB_EventType_LeftButtonDown
                  *This\MainBoard\RefreshLeftButtonState(#True)
                  
                Case #PB_EventType_LeftButtonUp
                  *This\MainBoard\RefreshLeftButtonState(#False)
                  
                Case #PB_EventType_MouseMove
                  *This\MainBoard\RefreshDraggedCardPosition()
                  
              EndSelect
              
            Case #CanvasArchiveBoard
              *This\ArchiveBoard\RefreshFlyingOverState()
              
              Select EventType()
                  
                Case #PB_EventType_LeftButtonDown
                  *This\ArchiveBoard\RefreshLeftButtonState(#True)
                  
                Case #PB_EventType_LeftButtonUp
                  *This\ArchiveBoard\RefreshLeftButtonState(#False)
                  
                Case #PB_EventType_MouseMove
                  *This\ArchiveBoard\RefreshDraggedCardPosition()
                  
              EndSelect
              
            Case #CanvasTrashBoard
              *This\TrashBoard\RefreshFlyingOverState()
              
              Select EventType()
                  
                Case #PB_EventType_LeftButtonDown
                  *This\TrashBoard\RefreshLeftButtonState(#True)
                  
                Case #PB_EventType_LeftButtonUp
                  *This\TrashBoard\RefreshLeftButtonState(#False)
                  
                Case #PB_EventType_MouseMove
                  *This\TrashBoard\RefreshDraggedCardPosition()
                  
              EndSelect
              
            Case #ButtonNew
              CreateNewProjectWindow(*This)
              
            Case #ButtonOpen
              OpenProjectButtonHandler(*This)
              
            Case #ButtonSave
              SaveProjectButtonHandler(*This)
              
            Case #ButtonOptions
              OptionsSettingsWindow(*This)
              
            Case #ButtonAddCard
              AddCardWindow(*This)
              
            Case #ButtonEditCard
              EditCardWindow(*This)
              
            Case #ButtonRemoveCard
              RemoveCardButtonHandler(*This)
              
            Case #ButtonMoveCard
              MoveCardButtonHandler(*This)
              
            Case #ButtonArchive
              ArchivesManagerWindow(*This)
              
            Case #ButtonTrash
              TrashManagerWindow(*This.Private_Members)
              
            Case #ButtonNewProjectCreate
              ButtonNewProjectCreateHandler(*This)
              CloseWindow(#NewProjectWindow)
              
            Case #ButtonNewProjectCancel
              CloseWindow(#NewProjectWindow)
              
            Case #ButtonAddCardCreate
              ButtonAddCardHandler(*This)
              CloseWindow(#AddCardWindow)
              
            Case #ButtonAddCardCancel
              CloseWindow(#AddCardWindow)
              
            Case #ButtonEditCardOK
              ButtonEditCardOkHandler(*This)
              CloseWindow(#EditCardWindow)
              
            Case #ButtonEditCardCancel
              CloseWindow(#EditCardWindow)
              
            Case #ButtonMoveCardOK
              ButtonMoveCardOkHandler(*This)
              CloseWindow(#MoveCardWindow)
              
            Case #ButtonMoveCardCancel
              CloseWindow(#MoveCardWindow)
              
            Case #ColorPreviewBorderColor To #ColorPreviewFlyOverBorderColor
              If EventType() = #PB_EventType_LeftClick
                AskNewColor(*This, EventGadget())
              EndIf
              
            Case #ButtonChooseFont
              AskNewFont(*This)
              
            Case #ButtonOptionsSettingsOK
              OptionsSettingsOK(*This)
              CloseOptionsSettings()
              
            Case #ButtonOptionsSettingsCancel
              CloseOptionsSettings()
              
            Case #ButtonEmptyArchive
              EmptyArchiveButtonHandler(*This)
              
            Case #ButtonDeleteCardFromArchive
              DeleteCardFromArchiveButtonHandler(*This)
              
            Case #ButtonRestoreCardFromArchive  
              UnarchiveCardFromTheArchiveButtonHandler(*This)
              
            Case #ButtonCloseArchiveManager
              CloseArchiveManager(*This)
              
            Case #ButtonEmptyTrash
              EmptyTrashButtonHandler(*This)
              
            Case #ButtonDeleteCardFromTrash
              DeleteCardFromTrashButtonHandler(*This)
              
            Case #ButtonRestoreCardFromTrash
              RestoreCardFromTheTrashButtonHandler(*This)
              
            Case #ButtonCloseTrashManager
              CloseTrashManager(*This)
              
          EndSelect
          
        Case #PB_Event_CloseWindow
          
          Select EventWindow()
              
            Case #MainWindow
              Exit_Condition = #True
              
            Case #NewProjectWindow
              CloseWindow(#NewProjectWindow)
              
            Case #OptionsSettingsWindow
              CloseOptionsSettings()
              
            Case #AddCardWindow
              CloseWindow(#AddCardWindow)
              
            Case #EditCardWindow
              CloseWindow(#EditCardWindow)
              
            Case #MoveCardWindow
              CloseWindow(#MoveCardWindow)
              
            Case #ArchiveWindow
              CloseArchiveManager(*This)
              
            Case #TrashWindow
              CloseTrashManager(*This)
              
          EndSelect
          
        Case #PB_Event_SizeWindow, #PB_Event_MaximizeWindow
          MainWindowSizeChangeManager(*This)
          
      EndSelect
      
    Until Exit_Condition = #True
    
  EndProcedure
  
  ; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  ; <<<<< The shutdown routine <<<<<
  
  Procedure Shutdown(*This.Private_Members)
    
    If *This\Project\GetProjectFileLoaded() = #True
      *This\Project\XML_CreateFile()
    EndIf
    
    *This\MainWindowSettings\SetIntegers("PosX", WindowX(#MainWindow))
    *This\MainWindowSettings\SetIntegers("PosY", WindowY(#MainWindow))
    *This\MainWindowSettings\SetIntegers("Width", WindowWidth(#MainWindow))
    *This\MainWindowSettings\SetIntegers("Height", WindowHeight(#MainWindow))
    
    CreatePrefs(*This)
    CloseWindow(#MainWindow)
    
  EndProcedure
  
  ; <<<<<<<<<<<<<<<<<<<<<<<<<<
  ; <<<<< The Destructor <<<<<
  
  Procedure Free(*This.Private_Members)
    
    If *This\MainWindowSettings <> #Null
      *This\MainWindowSettings\Free()
    EndIf
    
    If *This\GeneralSettings <> #Null
      *This\GeneralSettings\Free()
    EndIf
    
    If *This\MainBoard <> #Null
      *This\MainBoard\Free()
    EndIf
    
    If *This\TrashButtonCtrl
      *This\TrashButtonCtrl\Free()
    EndIf
    
    If *This\Project <> #Null
      *This\Project\Free()
    EndIf
    
    FreeStructure(*This)
    
  EndProcedure
  
  ; <<<<<<<<<<<<<<<<<<<<<<<<<<<
  ; <<<<< The Constructor <<<<<
  
  Procedure.i New()
    
    UsePNGImageDecoder()
    
    *This.Private_Members = AllocateStructure(Private_Members)
    *This\VirtualTable = ?START_METHODS
    
    *This\InstallPath = GetPathPart(ProgramFilename())
    
    CompilerSelect #PB_Compiler_OS
        
      CompilerCase #PB_OS_Windows 
        *This\UserPath = GetEnvironmentVariable("APPDATA") + "\DevBoard\"
        
      CompilerCase #PB_OS_Linux
        *This\UserPath = GetHomeDirectory() + ".devboard/"
        
      CompilerCase #PB_OS_MacOS
        *This\UserPath = GetHomeDirectory() + ".devboard/" ; This might be wrong
        
    CompilerEndSelect
    
    CreateDirectory(*This\UserPath)
    
    LanguagePath.s = *This\InstallPath + "language" + #PS$
    
    If FindString(GetEnvironmentVariable("LANGUAGE"), "fr")
      LanguageName.s = "Français"
    Else
      LanguageName = "English"
    EndIf
    
    *This\Language = Language::New(LanguagePath, LanguageName)
    
    *This\PrefsFileName = *This\UserPath + "DevBoard.prefs"
    
    *This\MainWindowSettings = WindowSettings::New()
    *This\MainWindowSettings\SetIntegers("PosX", 50)
    *This\MainWindowSettings\SetIntegers("PosY", 50)
    *This\MainWindowSettings\SetIntegers("Width", 800)
    *This\MainWindowSettings\SetIntegers("Height", 600)    
    *This\MainWindowSettings\SetIntegers("MinWidth", 800)
    *This\MainWindowSettings\SetIntegers("MinHeight", 600) 
    
    *This\GeneralSettings = Setting::New()
    *This\GeneralSettings\SetDeltaTimeSetting(Setting::#DeltaTimeSetting_30_Days)
    
    CompilerSelect #PB_Compiler_OS
        
      CompilerCase #PB_OS_Windows 
        *This\GeneralSettings\SetFontName("Arial")
        
      CompilerCase #PB_OS_Linux
        *This\GeneralSettings\SetFontName("Cantarell") ; If you are using Ubuntu maybe change the font name to "Ubuntu"
        
      CompilerCase #PB_OS_MacOS
        *This\GeneralSettings\SetFontName("Arial") ; This might be wrong
        
    CompilerEndSelect
    
    *This\GeneralSettings\SetFontSize(14)
    
    *This\GeneralSettings\SetBorderColor(RGBA(25, 25, 25, 255))
    *This\GeneralSettings\SetListBackColor(RGBA(225, 225, 225, 255))
    *This\GeneralSettings\SetCardBackColor(RGBA(255, 255, 255, 255))
    *This\GeneralSettings\SetTextColor(RGBA(0, 0, 0, 255))
    *This\GeneralSettings\SetSelectedBorderColor(RGBA(255, 100, 0, 255))
    *This\GeneralSettings\SetFlyOverBorderColor(RGBA(0, 255, 0, 255))
    
    *This\Project = Project::New()
    
    *This\MainBoard = BoardDrawingSystem::New(#ScrollAreaBoard, #CanvasBoard, *This\GeneralSettings, @MoveCardBetweenLists(), *This)
    *This\MainBoard\AddBoard("Ideas", "Ideas")
    *This\MainBoard\AddBoard("InProgress", "InProgress")
    *This\MainBoard\AddBoard("Completed", "Completed")
    *This\MainBoard\AddBoard("Abandoned", "Abandoned")
    
    *This\ArchiveBoard = BoardDrawingSystem::New(#ScrollAreaArchiveBoard, #CanvasArchiveBoard, *This\GeneralSettings, #Null, #Null)
    *This\ArchiveBoard\AddBoard("Archive", "Archive")
    
    *This\TrashBoard = BoardDrawingSystem::New(#ScrollAreaTrashBoard, #CanvasTrashBoard, *This\GeneralSettings, #Null, #Null)
    *This\TrashBoard\AddBoard("Trash", "Trash")
    
    If FileSize(*This\PrefsFileName) = -1
      CreatePrefs(*This)
    Else
      OpenPrefs(*This)
    EndIf
    
    *This\Language\LoadFile()
    
    LoadImage(#ButtonNew, *This\InstallPath + "icons" + #PS$ + "New - 32.png")
    LoadImage(#ButtonOpen, *This\InstallPath + "icons" + #PS$ + "Open - 32.png")
    LoadImage(#ButtonSave, *This\InstallPath + "icons" + #PS$ + "Save - 32.png")
    LoadImage(#ButtonOptions, *This\InstallPath + "icons" + #PS$ + "Options - 32.png")
    LoadImage(#ButtonAddCard, *This\InstallPath + "icons" + #PS$ + "Plus - 32.png")
    LoadImage(#ButtonEditCard, *This\InstallPath + "icons" + #PS$ + "Edit - 32.png")
    LoadImage(#ButtonRemoveCard, *This\InstallPath + "icons" + #PS$ + "Minus - 32.png")
    LoadImage(#ButtonMoveCard, *This\InstallPath + "icons" + #PS$ + "Move Card - 32.png")

    *This\ArchiveButtonCtrl = TwinState::New(#ButtonArchive, *This\InstallPath + "icons" + #PS$, "Archive Empty - 32.png", "Archive Full - 32.png", 0)
    *This\TrashButtonCtrl = TwinState::New(#ButtonTrash, *This\InstallPath + "icons" + #PS$, "Trash Empty - 32.png", "Trash Full - 32.png", 0)
    
    ProcedureReturn *This
  EndProcedure
  
  ; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
  ; <<<<< The Virtual Table Entries <<<<<
  
  DataSection
    START_METHODS:
    Data.i @CreateWindow()
    Data.i @EventManager()
    Data.i @Shutdown()
    Data.i @Free()
    END_METHODS:
  EndDataSection
  
  EnableDebugger
  
EndModule

; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
; <<<<< Code generated in : 00.001 seconds (162000.00 lines/second) <<<<<
; <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

; <<<<<<<<<<<<<<<<<<<<<<<
; <<<<< END OF FILE <<<<<
; <<<<<<<<<<<<<<<<<<<<<<<
; IDE Options = PureBasic 6.11 LTS (Linux - x64)
; Folding = -wbe0----
; EnableXP
; CompileSourceDirectory